### ISSUE TITLE
RealSense Experimental Release

### ISSUE THREAD

**Issue by ddiakopoulos** [teknotus/depthview#9]
It should be noted that at the Intel Developer Forum 2015, RealSense announced experimental support for F200 and R200, OSX + Linux that will be available on a "soon" timescale: https://software.intel.com/en-us/articles/what-if-experimental-software

**Comment by teknotus** [comment]
I see that there is a ROS release. https://github.com/PercATI/RealSense-ROS lists Linux as a requirement. It includes a kernel patch that looks a lot like mine, but with formats for the R200.

**Comment by floe** [comment]
For the record, the correct repository is https://github.com/PercATI/RealSense_ROS - appears to be from Intel, actually. And there's a rather well hidden binary userspace driver floating around at https://github.com/kaorun55/RealSense-ROS/tree/master/f200_install .

It's pretty interesting to look at https://github.com/kaorun55/RealSense-ROS/blob/master/f200_install/include/ivcamParameterReader.h - seems to give most of the data required to perform depth <-> color mapping.

**Comment by teknotus** [comment]
@floe The link I used in the earlier comment was correct, but then the whole archive got deleted, and reposted with the underscore, and missing F200 support. The well hidden repository is from when someone forked the original repository before it got deleted.

**Comment by floe** [comment]
@teknotus ah, interesting, thanks. Still, the discussion at https://github.com/PercATI/RealSense_ROS/issues/8 seems to indicate that Intel hasn't given up on an open-source Linux solution.

**Comment by teknotus** [comment]
@floe intel is the number one corporate supporter of free software in the world so it has always seemed probable to me that they would release something eventually. I don't have the kind of reputation to uphold that a big company does so I had nothing to lose by releasing a partial solution. I'm months ahead at releasing something, but have plenty of technical debt.

**Comment by ddiakopoulos** [comment]
Ping! https://github.com/IntelRealSense/librealsense

**Comment by floe** [comment]
This comes _exactly_ at the right moment. Kudos to Intel and @AmitMoran, cloning now :-)

**Comment by floe** [comment]
... and just for the record, kudos to @teknotus for probably poking Intel sufficiently to do this release :-)
